// Mock data for Cocina
// All copy in Spanish (Spain). Real Unsplash food URLs.

const RECIPES = [
  {
    id: 'r1',
    title: 'Lentejas con verduras de la abuela',
    cover: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    source: 'instagram',
    sourceUrl: 'https://instagram.com/p/abc',
    sourceLabel: '@cocina_de_eva',
    favorite: true,
    timeMin: 55,
    servings: 4,
    difficulty: 'Fácil',
    tags: ['legumbres', 'guiso', 'invierno'],
    lists: ['favoritas', 'rapidas'],
    addedDays: 2,
    ingredients: [
      { qty: 300, unit: 'g', name: 'lentejas pardinas' },
      { qty: 1, unit: '', name: 'cebolla grande' },
      { qty: 2, unit: '', name: 'zanahorias' },
      { qty: 1, unit: '', name: 'pimiento verde' },
      { qty: 3, unit: 'dientes', name: 'ajo' },
      { qty: 1, unit: 'cda', name: 'pimentón dulce' },
      { qty: 2, unit: '', name: 'hojas de laurel' },
      { qty: 1, unit: 'l', name: 'caldo de verduras' },
      { qty: 4, unit: 'cdas', name: 'aceite de oliva virgen extra' },
    ],
    steps: [
      'Pica fina la cebolla, el pimiento y la zanahoria. Lamina los ajos.',
      'En una olla, sofríe la cebolla con un buen chorro de aceite a fuego medio durante 8 minutos hasta que esté translúcida.',
      'Añade el pimiento, la zanahoria y el ajo. Sofríe otros 5 minutos sin que se queme.',
      'Retira la olla del fuego y agrega el pimentón. Remueve rápido para que no se amargue.',
      'Vuelve al fuego, añade las lentejas, el laurel y el caldo. Lleva a ebullición.',
      'Baja a fuego suave y cocina tapado durante 35-40 minutos hasta que las lentejas estén tiernas.',
      'Sala al final, prueba y rectifica. Reposa 5 minutos antes de servir.',
    ],
    notes: 'Mejoran de un día para otro. Si quedan espesas, añade un poco de caldo al recalentar.',
  },
  {
    id: 'r2',
    title: 'Tarta de queso al horno',
    cover: 'https://images.unsplash.com/photo-1567327613485-fbc7bf196198?w=800&q=80',
    source: 'blog',
    sourceUrl: 'https://elcomidista.elpais.com/tarta-queso',
    sourceLabel: 'El Comidista',
    favorite: true,
    timeMin: 70,
    servings: 8,
    difficulty: 'Fácil',
    tags: ['postre', 'horno', 'queso'],
    lists: ['postres', 'favoritas'],
    addedDays: 5,
    ingredients: [
      { qty: 600, unit: 'g', name: 'queso crema' },
      { qty: 400, unit: 'ml', name: 'nata para montar (35% MG)' },
      { qty: 5, unit: '', name: 'huevos' },
      { qty: 200, unit: 'g', name: 'azúcar' },
      { qty: 1, unit: 'cda', name: 'harina' },
      { qty: 1, unit: 'pizca', name: 'sal' },
    ],
    steps: [
      'Precalienta el horno a 210°C con calor arriba y abajo.',
      'Forra un molde redondo de 20 cm con papel de horno mojado y arrugado.',
      'Bate el queso crema con el azúcar hasta que quede sin grumos.',
      'Añade los huevos uno a uno, batiendo poco. No metas aire.',
      'Incorpora la nata, la harina y la pizca de sal. Mezcla suave.',
      'Vierte en el molde y hornea 45-50 minutos hasta que la superficie esté tostada y el centro tiemble.',
      'Deja enfriar en el molde y refrigera 4 horas antes de desmoldar.',
    ],
    notes: 'La de La Viña, sin truco. Si la quieres más cremosa, sácala cuando el centro tiemble como un flan.',
  },
  {
    id: 'r3',
    title: 'Wok de tofu y brócoli con jengibre',
    cover: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    source: 'manual',
    sourceUrl: null,
    sourceLabel: 'Escrita a mano',
    favorite: false,
    timeMin: 25,
    servings: 2,
    difficulty: 'Fácil',
    tags: ['vegetariano', 'rápido', 'wok', 'asiático'],
    lists: ['vegetarianas', 'rapidas'],
    addedDays: 1,
    ingredients: [
      { qty: 250, unit: 'g', name: 'tofu firme' },
      { qty: 1, unit: '', name: 'brócoli' },
      { qty: 3, unit: 'cm', name: 'jengibre fresco' },
      { qty: 2, unit: 'dientes', name: 'ajo' },
      { qty: 3, unit: 'cdas', name: 'salsa de soja' },
      { qty: 1, unit: 'cda', name: 'aceite de sésamo' },
      { qty: 1, unit: 'cdita', name: 'miel' },
      { qty: 1, unit: '', name: 'guindilla seca' },
    ],
    steps: [
      'Escurre bien el tofu y córtalo en dados. Sécalo con papel de cocina.',
      'Separa el brócoli en floretes. Pela y ralla el jengibre. Pica los ajos.',
      'Calienta un wok a fuego fuerte con el aceite de sésamo. Dora el tofu por todas las caras.',
      'Retira el tofu. En el mismo wok, saltea el brócoli 3 minutos.',
      'Añade el jengibre, ajo y guindilla. Saltea 30 segundos.',
      'Devuelve el tofu, riega con soja y miel. Saltea 1 minuto más.',
      'Sirve inmediatamente con arroz blanco o noodles.',
    ],
    notes: '',
  },
  {
    id: 'r4',
    title: 'Cordero al horno de Nochevieja',
    cover: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    source: 'instagram',
    sourceUrl: 'https://instagram.com/p/xyz',
    sourceLabel: '@martinberasategui',
    favorite: true,
    timeMin: 150,
    servings: 6,
    difficulty: 'Media',
    tags: ['horno', 'fiesta', 'carne'],
    lists: ['nochevieja', 'favoritas'],
    addedDays: 14,
    ingredients: [
      { qty: 1, unit: '', name: 'paletilla de cordero lechal (1.5 kg)' },
      { qty: 1, unit: 'cabeza', name: 'ajos' },
      { qty: 200, unit: 'ml', name: 'vino blanco' },
      { qty: 200, unit: 'ml', name: 'agua' },
      { qty: 1, unit: 'rama', name: 'romero fresco' },
      { qty: 1, unit: 'rama', name: 'tomillo fresco' },
      { qty: 50, unit: 'g', name: 'manteca de cerdo' },
      { qty: 1, unit: '', name: 'limón' },
    ],
    steps: [
      'Saca el cordero de la nevera 1 hora antes. Sécalo bien y sálalo generosamente.',
      'Precalienta el horno a 160°C.',
      'Coloca el cordero en una bandeja sobre la cabeza de ajos partida en dos.',
      'Embadúrnalo con la manteca, riega con el vino y el agua. Añade las hierbas.',
      'Hornea 90 minutos regando cada 20 minutos con el jugo.',
      'Sube el horno a 220°C y dóralo 15 minutos más.',
      'Reposa 10 minutos. Sirve con su jugo y un toque de limón.',
    ],
    notes: 'Fundamental que el cordero sea lechal de calidad. Pídelo en la carnicería con antelación.',
  },
  {
    id: 'r5',
    title: 'Ensalada de garbanzos, sandía y feta',
    cover: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80',
    source: 'blog',
    sourceUrl: 'https://www.directoalpaladar.com/ensalada',
    sourceLabel: 'Directo al Paladar',
    favorite: false,
    timeMin: 15,
    servings: 4,
    difficulty: 'Fácil',
    tags: ['vegetariano', 'rápido', 'verano', 'ensalada'],
    lists: ['vegetarianas', 'rapidas'],
    addedDays: 3,
    ingredients: [
      { qty: 400, unit: 'g', name: 'garbanzos cocidos' },
      { qty: 500, unit: 'g', name: 'sandía' },
      { qty: 200, unit: 'g', name: 'queso feta' },
      { qty: 1, unit: 'puñado', name: 'menta fresca' },
      { qty: 3, unit: 'cdas', name: 'aceite de oliva' },
      { qty: 1, unit: '', name: 'lima' },
      { qty: 1, unit: 'pizca', name: 'sal en escamas' },
    ],
    steps: [
      'Escurre y enjuaga los garbanzos. Sécalos con un paño.',
      'Corta la sandía en cubos de 2 cm, retirando las pepitas.',
      'Desmenuza el feta a mano en trozos irregulares.',
      'Mezcla todo en un bol grande con la menta picada.',
      'Aliña con aceite, ralladura y zumo de lima, y sal en escamas.',
      'Sirve inmediatamente, fría.',
    ],
    notes: '',
  },
  {
    id: 'r6',
    title: 'Coca de Sant Joan con frutas',
    cover: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    source: 'manual',
    sourceUrl: null,
    sourceLabel: 'Receta familiar',
    favorite: false,
    timeMin: 180,
    servings: 10,
    difficulty: 'Difícil',
    tags: ['postre', 'horno', 'tradicional'],
    lists: ['postres'],
    addedDays: 30,
    ingredients: [
      { qty: 500, unit: 'g', name: 'harina de fuerza' },
      { qty: 100, unit: 'g', name: 'azúcar' },
      { qty: 100, unit: 'ml', name: 'leche templada' },
      { qty: 25, unit: 'g', name: 'levadura fresca' },
      { qty: 3, unit: '', name: 'huevos' },
      { qty: 100, unit: 'g', name: 'mantequilla' },
      { qty: 1, unit: '', name: 'ralladura de limón' },
      { qty: 200, unit: 'g', name: 'frutas confitadas' },
      { qty: 50, unit: 'g', name: 'piñones' },
    ],
    steps: [
      'Disuelve la levadura en la leche templada con una cucharada de azúcar. Reposa 10 minutos.',
      'Mezcla harina, azúcar restante y ralladura. Añade los huevos y la mezcla de leche.',
      'Amasa 10 minutos. Incorpora la mantequilla blanda en trozos y amasa otros 10.',
      'Levado de 1.5 horas hasta que doble.',
      'Estira en bandeja, decora con frutas y piñones. Levado final de 30 minutos.',
      'Pinta con huevo batido y espolvorea azúcar. Hornea a 180°C, 25 minutos.',
    ],
    notes: 'Aguanta 3 días envuelta en film.',
  },
  {
    id: 'r7',
    title: 'Pasta carbonara como en Roma',
    cover: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80',
    source: 'instagram',
    sourceUrl: 'https://instagram.com/p/carbo',
    sourceLabel: '@gennarocontaldo',
    favorite: true,
    timeMin: 20,
    servings: 2,
    difficulty: 'Media',
    tags: ['pasta', 'rápido', 'italiano'],
    lists: ['rapidas', 'favoritas'],
    addedDays: 7,
    ingredients: [
      { qty: 200, unit: 'g', name: 'spaghetti o rigatoni' },
      { qty: 100, unit: 'g', name: 'guanciale' },
      { qty: 2, unit: '', name: 'yemas de huevo' },
      { qty: 1, unit: '', name: 'huevo entero' },
      { qty: 50, unit: 'g', name: 'pecorino romano rallado' },
      { qty: 1, unit: 'cdita', name: 'pimienta negra recién molida' },
    ],
    steps: [
      'Pon a hervir agua abundante con sal para la pasta.',
      'Corta el guanciale en tiras y dóralo en sartén fría a fuego medio hasta que suelte la grasa y esté crujiente.',
      'Bate las yemas con el huevo, el pecorino y mucha pimienta. Reserva.',
      'Cuece la pasta al dente. Reserva un cazo de agua de cocción.',
      'Pasa la pasta a la sartén con el guanciale (fuera del fuego). Mezcla.',
      'Añade los huevos y un poco de agua de cocción. Remueve enérgicamente sin fuego para crear la crema.',
      'Sirve con más pecorino y pimienta. Sin nata, jamás.',
    ],
    notes: 'El secreto: la sartén fuera del fuego al añadir el huevo. Sin nata. Sin ajo. Sin cebolla.',
  },
  {
    id: 'r8',
    title: 'Crema de calabaza asada y jengibre',
    cover: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800&q=80',
    source: 'blog',
    sourceUrl: 'https://www.bonviveur.es/crema-calabaza',
    sourceLabel: 'Bon Viveur',
    favorite: false,
    timeMin: 50,
    servings: 4,
    difficulty: 'Fácil',
    tags: ['vegetariano', 'sopa', 'otoño'],
    lists: ['vegetarianas'],
    addedDays: 9,
    ingredients: [
      { qty: 1, unit: 'kg', name: 'calabaza' },
      { qty: 1, unit: '', name: 'cebolla' },
      { qty: 3, unit: 'cm', name: 'jengibre' },
      { qty: 500, unit: 'ml', name: 'caldo de verduras' },
      { qty: 100, unit: 'ml', name: 'leche de coco' },
      { qty: 3, unit: 'cdas', name: 'aceite de oliva' },
      { qty: 1, unit: 'pizca', name: 'comino' },
      { qty: 1, unit: 'pizca', name: 'sal y pimienta' },
    ],
    steps: [
      'Precalienta el horno a 200°C.',
      'Pela la calabaza y córtala en cubos. Cebolla en gajos.',
      'Coloca todo en una bandeja, riega con aceite, sal y pimienta. Asa 35 minutos.',
      'Pasa todo a una olla, añade jengibre rallado, caldo y comino.',
      'Cuece 10 minutos y tritura con batidora hasta que quede sedosa.',
      'Añade la leche de coco al final, sin que hierva. Rectifica de sal.',
    ],
    notes: '',
  },
  {
    id: 'r9',
    title: 'Tortilla de patata jugosa',
    cover: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=800&q=80',
    source: 'manual',
    sourceUrl: null,
    sourceLabel: 'De mi madre',
    favorite: true,
    timeMin: 40,
    servings: 4,
    difficulty: 'Media',
    tags: ['clásico', 'huevo', 'tapas'],
    lists: ['favoritas'],
    addedDays: 4,
    ingredients: [
      { qty: 6, unit: '', name: 'huevos camperos' },
      { qty: 4, unit: '', name: 'patatas medianas' },
      { qty: 1, unit: '', name: 'cebolla' },
      { qty: 300, unit: 'ml', name: 'aceite de oliva' },
      { qty: 1, unit: 'pizca', name: 'sal' },
    ],
    steps: [
      'Pela las patatas y córtalas en láminas finas e irregulares. Sálalas.',
      'Pica la cebolla en juliana fina.',
      'Confita patatas y cebolla en aceite a fuego medio-bajo durante 20 minutos. Que no doren, que se ablanden.',
      'Escurre bien y reserva el aceite.',
      'Bate los huevos con sal. Mezcla con las patatas y cebolla. Reposa 5 minutos.',
      'En una sartén pequeña con un poco de aceite, vierte la mezcla. 2 minutos a fuego fuerte.',
      'Da la vuelta con un plato. Otros 2 minutos. El centro tiene que quedar jugoso.',
    ],
    notes: 'Con cebolla siempre. Y poca cocción para que quede jugosa.',
  },
  {
    id: 'r10',
    title: 'Mousse de chocolate con flor de sal',
    cover: 'https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=800&q=80',
    source: 'instagram',
    sourceUrl: 'https://instagram.com/p/mousse',
    sourceLabel: '@yotam.ottolenghi',
    favorite: false,
    timeMin: 30,
    servings: 6,
    difficulty: 'Media',
    tags: ['postre', 'chocolate', 'sin horno'],
    lists: ['postres'],
    addedDays: 11,
    ingredients: [
      { qty: 200, unit: 'g', name: 'chocolate negro 70%' },
      { qty: 4, unit: '', name: 'huevos' },
      { qty: 50, unit: 'g', name: 'azúcar' },
      { qty: 200, unit: 'ml', name: 'nata para montar' },
      { qty: 1, unit: 'pizca', name: 'flor de sal' },
    ],
    steps: [
      'Funde el chocolate al baño maría. Reserva templado.',
      'Separa las claras de las yemas. Monta la nata.',
      'Bate las yemas con el azúcar hasta que blanqueen.',
      'Mezcla yemas con chocolate templado. Después incorpora la nata con movimientos envolventes.',
      'Monta las claras a punto de nieve y añádelas en 3 veces, suave.',
      'Reparte en copas. Frigo 4 horas. Termina con flor de sal antes de servir.',
    ],
    notes: '',
  },
  {
    id: 'r11',
    title: 'Salmorejo cordobés tradicional',
    cover: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800&q=80',
    source: 'blog',
    sourceUrl: 'https://elpais.com/salmorejo',
    sourceLabel: 'El País Gastronomía',
    favorite: false,
    timeMin: 15,
    servings: 4,
    difficulty: 'Fácil',
    tags: ['frío', 'verano', 'andaluz', 'rápido'],
    lists: ['rapidas'],
    addedDays: 6,
    ingredients: [
      { qty: 1, unit: 'kg', name: 'tomates muy maduros' },
      { qty: 200, unit: 'g', name: 'pan del día anterior' },
      { qty: 1, unit: 'diente', name: 'ajo' },
      { qty: 100, unit: 'ml', name: 'AOVE' },
      { qty: 1, unit: 'cdita', name: 'sal' },
      { qty: 1, unit: 'cda', name: 'vinagre de Jerez' },
      { qty: 2, unit: '', name: 'huevos cocidos (para servir)' },
      { qty: 100, unit: 'g', name: 'jamón serrano (para servir)' },
    ],
    steps: [
      'Escalda los tomates 30 segundos en agua hirviendo. Pélalos.',
      'Tritura tomate, ajo, sal y vinagre con la batidora. Cuela.',
      'Añade el pan en trozos. Espera 5 minutos a que se hidrate.',
      'Tritura todo añadiendo el aceite poco a poco hasta emulsionar.',
      'Refrigera al menos 2 horas. Sirve frío con huevo picado y jamón.',
    ],
    notes: '',
  },
  {
    id: 'r12',
    title: 'Risotto de setas y trufa',
    cover: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c6?w=800&q=80',
    source: 'manual',
    sourceUrl: null,
    sourceLabel: 'De un curso en Italia',
    favorite: false,
    timeMin: 45,
    servings: 4,
    difficulty: 'Media',
    tags: ['arroz', 'italiano', 'setas'],
    lists: ['nochevieja'],
    addedDays: 20,
    ingredients: [
      { qty: 320, unit: 'g', name: 'arroz arborio' },
      { qty: 400, unit: 'g', name: 'mezcla de setas' },
      { qty: 1, unit: '', name: 'cebolla pequeña' },
      { qty: 100, unit: 'ml', name: 'vino blanco seco' },
      { qty: 1.2, unit: 'l', name: 'caldo de pollo' },
      { qty: 80, unit: 'g', name: 'parmesano rallado' },
      { qty: 50, unit: 'g', name: 'mantequilla' },
      { qty: 1, unit: '', name: 'trufa negra (opcional)' },
    ],
    steps: [
      'Calienta el caldo y mantenlo a fuego suave.',
      'Saltea las setas en sartén caliente con un poco de mantequilla. Reserva.',
      'En la misma olla, pocha la cebolla picada con mantequilla 8 minutos.',
      'Añade el arroz, tuesta 2 minutos. Riega con el vino y deja evaporar.',
      'Añade caldo cazo a cazo, removiendo, hasta que el arroz esté al dente (18 min).',
      'Fuera del fuego, añade setas, parmesano y mantequilla fría. Mantequea.',
      'Sirve inmediatamente con trufa rallada por encima.',
    ],
    notes: 'El "mantecado" final es lo que hace la diferencia. No te saltes el reposo de 1 minuto al final.',
  },
];

const LISTS = [
  { id: 'favoritas', name: 'Favoritas de Eva', icon: '♥', color: '#E0524A', count: 5 },
  { id: 'vegetarianas', name: 'Vegetarianas', icon: '🌱', color: '#6B8E5A', count: 3 },
  { id: 'postres', name: 'Postres', icon: '🍰', color: '#D9A35A', count: 3 },
  { id: 'nochevieja', name: 'Nochevieja', icon: '✨', color: '#8B6FB8', count: 2 },
  { id: 'rapidas', name: 'Rápidas entre semana', icon: '⏱', color: '#5A8FB8', count: 4 },
];

const TAGS = [
  'vegetariano', 'sin gluten', 'rápido', 'horno', 'wok',
  'postre', 'pasta', 'arroz', 'verano', 'invierno', 'ensalada', 'sopa',
];

window.RECIPES = RECIPES;
window.LISTS = LISTS;
window.TAGS = TAGS;
